name: Test Modules via Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Validation
    runs-on: ubuntu-latest
    environment: Development
    env:
        TF_LOG: ERROR
        # Azure
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        # Naver Cloud
        NCLOUD_ACCESS_KEY: ${{ secrets.NCLOUD_ACCESS_KEY }}
        NCLOUD_SECRET_KEY: ${{ secrets.NCLOUD_SECRET_KEY }}
        NCLOUD_REGION: ${{ secrets.NCLOUD_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Plan  
        run: |
          source_branch="${{ github.head_ref }}"
          target_branch="${{ github.base_ref }}"
          echo "\e[0;35mFetching changes between $source_branch and $target_branch\e[0m"
          git fetch origin
          git checkout -b "$target_branch" origin/"$target_branch"
          git checkout -b "$source_branch" origin/"$source_branch"
          git diff --name-only "$target_branch" "$source_branch"
          changes=$(git diff --name-only "$target_branch" "$source_branch" | xargs -I {} dirname {} | grep -v "/example$" | sort -u)
          echo "\e[0;35mChanges detected in the following modules: $changes\e[0m"
          for module in $changes; do
            if [ -d "$module/example" ]; then
              echo -e "\e[0;35mRunning terraform plan for module: $module\e[0m"
              terraform -chdir="$module/example" init
              terraform -chdir="$module/example" plan -no-color -out="plan_file"
              cat plan_file
            else
                echo -e "\e[38;5;214mNo 'example' folder found in module: $module\e[0m"
            fi
          done